version: '3.8'
services:
  api:
    container_name: ms-vecinet-auth
    build: .
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - .:/app
      - gradle-cache:/home/gradle/.gradle
volumes:
  gradle-cache:
