server:
  port: ${APP_PORT}
spring:
  application:
    name: auth
  data:
    mongodb:
      uri: ${MONGO_URL}
      database: ${MONGO_DB}

# Configuracion de Swagger Open Api
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
  openapi:
    info:
      title: Vecinet API
      description: API documentation for Vecinet Authenticator
      version: v1.0.0
      contact:
        name: Vecinet Support
        url: http://vecinet.com/support
        email: support@vecinet.com
logging:
  level:
    org:
      springframework:
        security : DEBUG
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}