spring:
  application:
    name: ms-vecinet-auth
  data:
    mongodb:
      uri: ${MONGO_URL}
      database: ${MONGO_DB}

server:
  port: ${APP_PORT}
  servlet:
    context-path: /api/${spring.application.name}

# Configuracion de Swagger Open Api
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
  openapi:
    info:
      title: Vecinet API
      description: API documentation for Vecinet Authenticator
      version: v1.0.0
      contact:
        name: Vecinet Support
        url: http://vecinet.com/support
        email: support@vecinet.com
logging:
  level:
    org:
      springframework:
        security : DEBUG
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

# Eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}